version: "3.9"

services:
  crypto-microservice:
    build: .
    container_name: crypto-microservice
    env_file:
      - .env.prod
    ports:
      - "8002:8002"
    restart: unless-stopped
  auth-service:
    build: ./auth-service-dotnet
    container_name: auth-service
    ports:
      - "8001:8001" 

